### ISSUE TITLE
Make overriding of dictionaries and arrays possible

### ISSUE THREAD

**Issue by corvus-ch** [projectsyn/commodore#162]
## Context
The inventory hierarchy allows to add new keys to a dictionary, add values to an array and change scalar values. However it is not possible to override dictionaries and arrays as a whole.

This is an essential feature to effectively define sensible defaults within a component (for example labels, annotations, node selectors and many more).

## Alternatives

https://reclass.pantsfullofunix.net/configfile.html suggests one can place the file `reclass-config.yml` and allow _override list and dicts by empty entity_ (see https://github.com/kapicorp/reclass/blob/fb50054d6332167c34dd2ae8b486943dd9c28746/README-extensions.rst#allow-override-list-and-dicts-by-empty-entitynone-instead-of-merge). However this does not work. It seems that the file does not get read.

```
poetry run commodore catalog compile $CLUSTER_ID --local
Running in local mode
 > Will use existing inventory, dependencies, and catalog
 > Using target: cluster
 > Reconstructing Cluster API data from target
Registering config...
Registering components...
Configuring catalog repo...
Inventory reclass error: -> cluster
   Cannot merge scalar over dictionary, at openshift4_registry:config:nodeSelector, in yaml_fs://./commodore/inventory/classes/defaults/openshift4-registry.yml; yaml_fs://./commodore/inventory/classes/t-ancient-morning-1764/openshift4.yml; yaml_fs://./commodore/inventory/classes/t-ancient-morning-1764/c-old-fire-5788.yml
Traceback (most recent call last):
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/kapitan/resources.py", line 338, in inventory_reclass
    cached.inv = _reclass.inventory()
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/kapitan/reclass/reclass/core.py", line 254, in inventory
    entities[n] = self._nodeinfo(n, inventory)
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/kapitan/reclass/reclass/core.py", line 229, in _nodeinfo
    node.interpolate(inventory)
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/kapitan/reclass/reclass/datatypes/entity.py", line 79, in interpolate
    self._parameters.interpolate(inventory)
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/kapitan/reclass/reclass/datatypes/parameters.py", line 294, in interpolate
    self._interpolate_inner(path, inventory)
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/kapitan/reclass/reclass/datatypes/parameters.py", line 321, in _interpolate_inner
    new = self._interpolate_render_value(path, value, inventory)
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/kapitan/reclass/reclass/datatypes/parameters.py", line 327, in _interpolate_render_value
    new = value.render(self._base, inventory)
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/kapitan/reclass/reclass/values/valuelist.py", line 146, in render
    raise TypeMergeError(self._values[n], self._values[n-1], self.uri)
reclass.errors.TypeMergeError: -> cluster
   Cannot merge scalar over dictionary, at openshift4_registry:config:nodeSelector, in yaml_fs://./commodore/inventory/classes/defaults/openshift4-registry.yml; yaml_fs://./commodore/inventory/classes/t-ancient-morning-1764/openshift4.yml; yaml_fs://./commodore/inventory/classes/t-ancient-morning-1764/c-old-fire-5788.yml
```

**Comment by simu** [comment]
Looking at the code, I've found the following: https://github.com/kapicorp/reclass/blob/2585bfc620ddd8c2cd7d159c4eb6d117a526a819/reclass/defaults.py#L44-L49

According to the implementation, reclass looks for the `reclass-config.yml` file also in the inventory root directory (`inventory/` for Commodore). I'm not sure what the result of `os.path.dirname(sys.argv[0])` is when running Commodore via poetry.

**Comment by corvus-ch** [comment]
Yes, placing the `reclass-config.yml` in `inventory/` does work. However, this does not work as expected. I can then not override that key with new values.

```
poetry run commodore catalog compile $CLUSTER_ID --local
Running in local mode
 > Will use existing inventory, dependencies, and catalog
 > Using target: cluster
 > Reconstructing Cluster API data from target
Registering config...
Registering components...
Configuring catalog repo...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "./commodore/commodore/cli.py", line 143, in main
    commodore.main(prog_name='commodore', auto_envvar_prefix='COMMODORE')
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./commodore/commodore/cli.py", line 84, in compile_catalog
    _compile(config, cluster)
  File "./commodore/commodore/compile.py", line 143, in compile
    kapitan_inventory = inventory_reclass('inventory')['nodes'][target_name]
  File "~/Library/Caches/pypoetry/virtualenvs/commodore-4c9QClYe-py3.8/lib/python3.8/site-packages/kapitan/resources.py", line 319, in inventory_reclass
    uri_path = os.path.join(inventory_path, uri_val)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```

**Comment by simu** [comment]
Some debugging shows that Kapitan won't work correctly unless all the default configuration values for reclass are replicated in `reclass-config.yml`, if the file exists. I've got overriding a dict with `~` to work with the following `reclass-config.yml`: 

```
nodes_uri: targets
classes_uri: classes
storage_type: yaml_fs
compose_node_name: False
allow_none_override: True
```

**Comment by corvus-ch** [comment]
I can confirm that this configuration set does work.

I suggest to have this written by commodore when running compile.

Plus we need to document how this is to be used.

Level Zero: set value to `~`
Level One: set desired value.

While this is technically working, it is a bad developer/user experience. Can we do better? Ideally we would be able to handle this all within the same level of the hierarchy.

**Comment by srueg** [comment]
This is alredy set upstream, but only released in an RC:
https://github.com/deepmind/kapitan/pull/562

**Comment by simu** [comment]
> This is alredy set upstream, but only released in an RC:
> [deepmind/kapitan#562](https://github.com/deepmind/kapitan/pull/562)

I vaguely remembered that, but I wasn't able to find the relevant PR anymore :see_no_evil:

**Comment by srueg** [comment]
I just found a solution for this:
If you prepend `~` to a key, the dict or array will be overridden instead of merged 🎉 

for example:

```
parameters:
  openshift4_authentication:
    ~identityProviders:
    - name: Keycloak
      type: OpenID
      mappingMethod: claim
```

This will instead of extending the `parameters.openshift4_authentication.identityProviders` array, override it completely with only one item.

**Comment by srueg** [comment]
See https://github.com/kapicorp/reclass/blob/develop/reclass/defaults.py#L54 and https://github.com/kapicorp/reclass/blob/develop/reclass/settings.py#L25

**Comment by srueg** [comment]
I'll close this since we have a solution with the `~` prefix.
