### ISSUE TITLE
commodore compile error

### ISSUE THREAD

**Issue by nunojusto** [projectsyn/commodore#196]
When trying to compile with commodore to get all cluster info in a clean folder.
Note: I'm not using poetry

## Steps to Reproduce the Problem
Note: I'm not putting env var values here, for security reasons.
```
docker pull docker.io/projectsyn/commodore:latest

commodore () {
    mkdir -p inventory/classes/global dependencies/lib compiled/ catalog/ cache/
    docker run \
    --interactive=true \
    --tty \
    --rm \
    --user="$(id -u):$(id -u)" \
    --volume "$HOME"/.ssh:/app/.ssh:ro \
    --volume "$PWD"/compiled/:/app/compiled/ \
    --volume "$PWD"/catalog/:/app/catalog \
    --volume "$PWD"/dependencies/:/app/dependencies/ \
    --volume "$PWD"/inventory/:/app/inventory/ \
    --volume ~/.gitconfig:/app/.gitconfig:ro \
    --volume "$PWD"/cache:/app/.cache \
    -e COMMODORE_API_URL=$COMMODORE_API_URL \
    -e COMMODORE_GLOBAL_GIT_BASE=$COMMODORE_GLOBAL_GIT_BASE \
    -e COMMODORE_API_TOKEN=$COMMODORE_API_TOKEN \
    projectsyn/commodore:latest \
    $*
}

commodore catalog compile ${CLUSTER_ID}
```

## Actual Behavior
and the output is this:
```
...
Fetching components...
Updating Kapitan target...
Updating cluster catalog...
Updating Jsonnet libraries...
Traceback (most recent call last):
  File "/usr/local/bin/commodore", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/commodore/cli.py", line 174, in main
    commodore.main(prog_name='commodore', auto_envvar_prefix='COMMODORE')
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/commodore/cli.py", line 85, in compile_catalog
    _compile(config, cluster)
  File "/usr/local/lib/python3.8/site-packages/commodore/compile.py", line 159, in compile
    write_jsonnetfile(config)
  File "/usr/local/lib/python3.8/site-packages/commodore/dependency_mgmt.py", line 233, in write_jsonnetfile
    with open("jsonnetfile.json", "w") as file:
PermissionError: [Errno 13] Permission denied: 'jsonnetfile.json'
```

## Expected Behavior
A clean compile that I can use to init terraform

**Comment by nunojusto** [comment]
I think it needs to write that jsonnetfile.json file inside a folder that we can control.￼
￼Because having it on / (root) we cannot change that folder id permissions. And so and then we cannot write jsonnetfile.json that there

**Comment by corvus-ch** [comment]
Please try to define the `commodore()` functions as following:

```bash
commdore() {
  docker run \
    --interactive=true \
    --tty \
    --rm \
    --user="$(id -u):$(id -u)" \
    --volume "${HOME}/.ssh:/app/.ssh:ro" \
    --volume "${HOME}/.gitconfig:/app/.gitconfig:ro" \
    --volume "${PWD}:/app/data" \
    --workdir /app/data \
    -e COMMODORE_API_URL=$COMMODORE_API_URL \
    -e COMMODORE_GLOBAL_GIT_BASE=$COMMODORE_GLOBAL_GIT_BASE \
    -e COMMODORE_API_TOKEN=$COMMODORE_API_TOKEN \
    projectsyn/commodore:latest \
    $*
}
```

**Comment by corvus-ch** [comment]
Now that the `mkdir` is no longer required, we can also switch back to an alias.

```bash
alias commodore='docker run --interactive=true --tty --rm --user="$(id -u)" --volume "${HOME}/.ssh:/app/.ssh:ro" --volume "${HOME}/.gitconfig:/app/.gitconfig:ro" --volume "${PWD}:/app/data" --workdir /app/data -e COMMODORE_API_URL=$COMMODORE_API_URL -e COMMODORE_GLOBAL_GIT_BASE=$COMMODORE_GLOBAL_GIT_BASE -e COMMODORE_API_TOKEN=$COMMODORE_API_TOKEN projectsyn/commodore:latest'
```

This alias worked for me both on macOS with Docker for Mac and on Ubuntu Bionic (vagrant box).

**Comment by nunojusto** [comment]
I can confirm that it works.
Even the 'cache' issue is gone. Great work @corvus-ch 
This can be closed

**Comment by corvus-ch** [comment]
I will keep this open. The example at https://openshift.docs.vshn.ch/oc4/how-tos/cloudscale/install.html#_terraform_cluster_config is still wrong.
