### ISSUE TITLE
FileExistsError on catalog compile

### ISSUE THREAD

**Issue by mhutter** [projectsyn/commodore#233]
Catalog compile jobs often error because of

    FileExistsError: [Errno 17] File exists: '/tmp/tmpq5eh6tin.kapitan/extracted

Sometimes, the job succeeds after some tries, sometimes the job succeeds after re-triggering the job (because the K8s job will correctly fail after 3 attempts), and sometimes nothing helps.

Note: I triggered a recompile for ALL clusters for a customer, and only the clusters that had a (successful) catalog compilation within the last 4h failed.

See the `commodore-job-runner` on synfra.

## Steps to Reproduce the Problem

1. Trigger a compile job

## Actual Behavior
```
...
Dependency https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.7/config/v1.7/aws-k8s-cni.yaml: successfully fetched
Dependency https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/release-1.7/config/v1.7/aws-k8s-cni.yaml: saved to dependencies/eks-addon-manager/manifests/aws-k8s-cni.yaml
Dependency https://redhat-cop.github.io/resource-locker-operator/resource-locker-operator/resource-locker-operator-v0.1.2.tgz: successfully fetched
Dependency https://redhat-cop.github.io/resource-locker-operator/resource-locker-operator/resource-locker-operator-v0.1.2.tgz: extracted to dependencies/resource-locker/helmcharts
Dependency https://charts.appuio.ch/k8up-0.6.1.tgz: successfully fetched
Dependency https://kubernetes-charts.storage.googleapis.com/prometheus-pushgateway-1.2.13.tgz: successfully fetched
Dependency https://charts.appuio.ch/k8up-0.6.1.tgz: extracted to dependencies/backup-k8up/helmcharts
Unknown (Non-Kapitan) Error occurred
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.8/site-packages/kapitan/dependency_manager/base.py", line 176, in fetch_http_dependency
    os.makedirs(unpack_output)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/tmpq5eh6tin.kapitan/extracted'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kapitan/targets.py", line 119, in compile_targets
    fetch_dependencies(
  File "/usr/local/lib/python3.8/site-packages/kapitan/dependency_manager/base.py", line 92, in fetch_dependencies
    [p.get() for p in pool.imap_unordered(http_worker, http_deps.items()) if p]
  File "/usr/local/lib/python3.8/site-packages/kapitan/dependency_manager/base.py", line 92, in <listcomp>
    [p.get() for p in pool.imap_unordered(http_worker, http_deps.items()) if p]
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
FileExistsError: [Errno 17] File exists: '/tmp/tmpq5eh6tin.kapitan/extracted'


[Errno 17] File exists: '/tmp/tmpq5eh6tin.kapitan/extracted'
```

## Expected Behavior

Successful catalog compilation

**Comment by simu** [comment]
Fixed in https://github.com/deepmind/kapitan/pull/608 but we're blocked from updating Kapitan due to other issues, see #203
